#!/bin/sh
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)


sudo /usr/sbin/cron
export JAVA_HOME=/opt/jdk
export PATH=$PATH:/opt/jdk/bin
cd /home/dsl/workspace
/usr/bin/java -Djdk.util.jar.enableMultiRelease=false -jar /opt/structurizr.war /home/dsl/workspace








