---
name: "Continuous Integration"

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  ci-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_DOCKERFILE: true
          # DEFAULT_BRANCH: dev
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # DOCKERFILE_FILE_NAME: Containerfile

      - name: Set up packages 
        # QEMU for aarch64 (if using emulation)
        run: |
          sudo apt-get update
          sudo apt-get install --yes qemu-user-static binfmt-support podman
          sudo update-binfmts --enable qemu-aarch64
          
      - name: Repository registry login
        run: |
          echo "${{ secrets.DOCKERIO_TOKEN }}" | /usr/bin/podman login \
            --username "${{ secrets.DOCKERIO_REGISTRY }}" \
            --password-stdin docker.io

      - name: Build Container Image for aarch64 using Podman
        run: |
          /usr/bin/podman build --arch aarch64 --no-cache \
           --tag structurizr:dev --file Containerfile .


      - name: Push Container Image to Registry docker.io
        run: |
          P_IMG="docker.io/${{ secrets.DOCKERIO_REGISTRY }}"
          IMG="$P_IMG/structurizr:dev"
          /usr/bin/podman tag "structurizr:dev" $IMG 
          /usr/bin/podman push $IMG
          
      - name: Release Image to version/latest
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: |
          P_IMG="docker.io/${{ secrets.DOCKERIO_REGISTRY }}"
          IMG="$P_IMG/homepage:0.10.9"
          /usr/bin/podman tag "structurizr:dev" $IMG 
          /usr/bin/podman push $IMG
          IMG="$P_IMG/homepage:latest"
          /usr/bin/podman tag "structurizr:dev" $IMG 
          /usr/bin/podman push $IMG
